import type { Metadata } from "next";
import { site } from "./site";
import { absoluteUrl } from "./utils";

/**
 * `--ground` and `--d-ground` from globals.css, duplicated here because they
 * have to be.
 *
 * This is the one place on the site that breaks non-negotiable #5, and it
 * breaks it because a `<meta name="theme-color">` is read by the browser
 * before any stylesheet and cannot resolve a custom property. Without it the
 * address bar on a phone paints its own grey above the page.
 *
 * So the values are duplicated exactly once, in the open, and `pnpm contrast`
 * asserts each still equals the token it mirrors. A silent drift here is the
 * failure mode that block in globals.css already warns about; this makes it a
 * loud one.
 */
export const GROUND_HEX = "#fcfcfc";
export const GROUND_HEX_DARK = "#0c0d11";

/**
 * The localStorage key the theme toggle writes and the pre-paint script in
 * layout.tsx reads. Shared from here so the two cannot disagree — they run in
 * different files, at different times, and a typo in either one is a flash of
 * the wrong theme on every load.
 */
export const THEME_STORAGE_KEY = "vekto-theme";

/**
 * The card every route shares, generated by `src/app/opengraph-image.tsx`.
 *
 * One image for the whole site rather than one per route. A per-page card would
 * have to state something about that page, and for most of these routes the
 * only thing it could state is a title we would then be rendering twice — once
 * in the card and once in the post that carries it. The site-wide card carries
 * the three registry counts instead, which are true on every route.
 *
 * `metadataBase` in layout.tsx resolves this relative path to an absolute URL,
 * which is what the crawlers require.
 */
const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${site.name} — ${site.shortDescription}`,
} as const;

type BuildMetadataArgs = {
  title: string;
  description: string;
  /** Site-relative path, e.g. "/migrations/tibco-to-azure-logic-apps". */
  path: string;
  /** Omit for evergreen pages; set for articles and case studies. */
  publishedTime?: string;
  modifiedTime?: string;
  type?: "website" | "article";
  /** Set false for draft/unconfirmed pages so they never get indexed. */
  indexable?: boolean;
};

/**
 * Every page builds its metadata through here. That guarantees a canonical,
 * an OG image and a correctly suffixed title on all of them — the previous
 * site shipped a single unchanging <title> across every route.
 *
 * The OG image half of that sentence was aspirational for a long time: there
 * was no `images` key here, no `opengraph-image` route and nothing in
 * `public/`, while `twitter.card` was already `summary_large_image` with
 * nothing to fill it. `src/app/opengraph-image.tsx` is that image, and the
 * keys below are what point at it.
 */
export function buildMetadata({
  title,
  description,
  path,
  publishedTime,
  modifiedTime,
  type = "website",
  indexable = true,
}: BuildMetadataArgs): Metadata {
  const url = absoluteUrl(path);
  const fullTitle = path === "/" ? title : `${title} — ${site.name}`;

  return {
    title: fullTitle,
    description,
    alternates: { canonical: url },
    robots: indexable
      ? { index: true, follow: true }
      : { index: false, follow: false },
    openGraph: {
      title: fullTitle,
      description,
      url,
      siteName: site.name,
      locale: site.locale,
      type,
      images: [OG_IMAGE],
      ...(publishedTime ? { publishedTime } : {}),
      ...(modifiedTime ? { modifiedTime } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [OG_IMAGE.url],
    },
  };
}
